FROM nvidia/cuda:11.0.3-devel-ubuntu18.04

# apt-get install xorg-dev libglu1-mesa-dev python3-dev libsdl2-dev \
#     libc++-7-dev libc++abi-7-dev ninja-build libxi-dev libtbb-dev \
#     libosmesa6-dev libudev-dev autoconf libtool
